/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authenticatedIndexRouteImport } from './routes/(authenticated)/index'
import { Route as authenticatedStylesRouteImport } from './routes/(authenticated)/styles'
import { Route as authenticatedReportsRouteImport } from './routes/(authenticated)/reports'
import { Route as authenticatedPersonnelRouteImport } from './routes/(authenticated)/personnel'
import { Route as authenticatedMeRouteImport } from './routes/(authenticated)/me'
import { Route as authenticatedFormRouteImport } from './routes/(authenticated)/form'
import { Route as authenticatedProjectsRouteRouteImport } from './routes/(authenticated)/projects/route'
import { Route as authenticatedReportsIndexRouteImport } from './routes/(authenticated)/reports/index'
import { Route as authenticatedAccrualsIndexRouteImport } from './routes/(authenticated)/accruals/index'
import { Route as authenticatedProjectsEmployeeIdRouteRouteImport } from './routes/(authenticated)/projects/$employeeId/route'
import { Route as authenticatedProjectsEmployeeIdIndexRouteImport } from './routes/(authenticated)/projects/$employeeId/index'
import { Route as authenticatedReportsReconciliationProjectNumberIndexRouteImport } from './routes/(authenticated)/reports/reconciliation/$projectNumber/index'
import { Route as authenticatedProjectsEmployeeIdProjectNumberIndexRouteImport } from './routes/(authenticated)/projects/$employeeId/$projectNumber/index'
import { Route as authenticatedReportsReconciliationProjectNumberDetailRouteImport } from './routes/(authenticated)/reports/reconciliation/$projectNumber/detail'
import { Route as authenticatedProjectsEmployeeIdProjectNumberTransactionsRouteImport } from './routes/(authenticated)/projects/$employeeId/$projectNumber/transactions'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedIndexRoute = authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedStylesRoute = authenticatedStylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedReportsRoute = authenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedPersonnelRoute = authenticatedPersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedMeRoute = authenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedFormRoute = authenticatedFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedProjectsRouteRoute =
  authenticatedProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedReportsIndexRoute =
  authenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedReportsRoute,
  } as any)
const authenticatedAccrualsIndexRoute =
  authenticatedAccrualsIndexRouteImport.update({
    id: '/accruals/',
    path: '/accruals/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedProjectsEmployeeIdRouteRoute =
  authenticatedProjectsEmployeeIdRouteRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => authenticatedProjectsRouteRoute,
  } as any)
const authenticatedProjectsEmployeeIdIndexRoute =
  authenticatedProjectsEmployeeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedProjectsEmployeeIdRouteRoute,
  } as any)
const authenticatedReportsReconciliationProjectNumberIndexRoute =
  authenticatedReportsReconciliationProjectNumberIndexRouteImport.update({
    id: '/reconciliation/$projectNumber/',
    path: '/reconciliation/$projectNumber/',
    getParentRoute: () => authenticatedReportsRoute,
  } as any)
const authenticatedProjectsEmployeeIdProjectNumberIndexRoute =
  authenticatedProjectsEmployeeIdProjectNumberIndexRouteImport.update({
    id: '/$projectNumber/',
    path: '/$projectNumber/',
    getParentRoute: () => authenticatedProjectsEmployeeIdRouteRoute,
  } as any)
const authenticatedReportsReconciliationProjectNumberDetailRoute =
  authenticatedReportsReconciliationProjectNumberDetailRouteImport.update({
    id: '/reconciliation/$projectNumber/detail',
    path: '/reconciliation/$projectNumber/detail',
    getParentRoute: () => authenticatedReportsRoute,
  } as any)
const authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute =
  authenticatedProjectsEmployeeIdProjectNumberTransactionsRouteImport.update({
    id: '/$projectNumber/transactions',
    path: '/$projectNumber/transactions',
    getParentRoute: () => authenticatedProjectsEmployeeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/projects': typeof authenticatedProjectsRouteRouteWithChildren
  '/form': typeof authenticatedFormRoute
  '/me': typeof authenticatedMeRoute
  '/personnel': typeof authenticatedPersonnelRoute
  '/reports': typeof authenticatedReportsRouteWithChildren
  '/styles': typeof authenticatedStylesRoute
  '/': typeof authenticatedIndexRoute
  '/projects/$employeeId': typeof authenticatedProjectsEmployeeIdRouteRouteWithChildren
  '/accruals': typeof authenticatedAccrualsIndexRoute
  '/reports/': typeof authenticatedReportsIndexRoute
  '/projects/$employeeId/': typeof authenticatedProjectsEmployeeIdIndexRoute
  '/projects/$employeeId/$projectNumber/transactions': typeof authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute
  '/reports/reconciliation/$projectNumber/detail': typeof authenticatedReportsReconciliationProjectNumberDetailRoute
  '/projects/$employeeId/$projectNumber': typeof authenticatedProjectsEmployeeIdProjectNumberIndexRoute
  '/reports/reconciliation/$projectNumber': typeof authenticatedReportsReconciliationProjectNumberIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/projects': typeof authenticatedProjectsRouteRouteWithChildren
  '/form': typeof authenticatedFormRoute
  '/me': typeof authenticatedMeRoute
  '/personnel': typeof authenticatedPersonnelRoute
  '/styles': typeof authenticatedStylesRoute
  '/': typeof authenticatedIndexRoute
  '/accruals': typeof authenticatedAccrualsIndexRoute
  '/reports': typeof authenticatedReportsIndexRoute
  '/projects/$employeeId': typeof authenticatedProjectsEmployeeIdIndexRoute
  '/projects/$employeeId/$projectNumber/transactions': typeof authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute
  '/reports/reconciliation/$projectNumber/detail': typeof authenticatedReportsReconciliationProjectNumberDetailRoute
  '/projects/$employeeId/$projectNumber': typeof authenticatedProjectsEmployeeIdProjectNumberIndexRoute
  '/reports/reconciliation/$projectNumber': typeof authenticatedReportsReconciliationProjectNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/(authenticated)/projects': typeof authenticatedProjectsRouteRouteWithChildren
  '/(authenticated)/form': typeof authenticatedFormRoute
  '/(authenticated)/me': typeof authenticatedMeRoute
  '/(authenticated)/personnel': typeof authenticatedPersonnelRoute
  '/(authenticated)/reports': typeof authenticatedReportsRouteWithChildren
  '/(authenticated)/styles': typeof authenticatedStylesRoute
  '/(authenticated)/': typeof authenticatedIndexRoute
  '/(authenticated)/projects/$employeeId': typeof authenticatedProjectsEmployeeIdRouteRouteWithChildren
  '/(authenticated)/accruals/': typeof authenticatedAccrualsIndexRoute
  '/(authenticated)/reports/': typeof authenticatedReportsIndexRoute
  '/(authenticated)/projects/$employeeId/': typeof authenticatedProjectsEmployeeIdIndexRoute
  '/(authenticated)/projects/$employeeId/$projectNumber/transactions': typeof authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute
  '/(authenticated)/reports/reconciliation/$projectNumber/detail': typeof authenticatedReportsReconciliationProjectNumberDetailRoute
  '/(authenticated)/projects/$employeeId/$projectNumber/': typeof authenticatedProjectsEmployeeIdProjectNumberIndexRoute
  '/(authenticated)/reports/reconciliation/$projectNumber/': typeof authenticatedReportsReconciliationProjectNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/projects'
    | '/form'
    | '/me'
    | '/personnel'
    | '/reports'
    | '/styles'
    | '/'
    | '/projects/$employeeId'
    | '/accruals'
    | '/reports/'
    | '/projects/$employeeId/'
    | '/projects/$employeeId/$projectNumber/transactions'
    | '/reports/reconciliation/$projectNumber/detail'
    | '/projects/$employeeId/$projectNumber'
    | '/reports/reconciliation/$projectNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/projects'
    | '/form'
    | '/me'
    | '/personnel'
    | '/styles'
    | '/'
    | '/accruals'
    | '/reports'
    | '/projects/$employeeId'
    | '/projects/$employeeId/$projectNumber/transactions'
    | '/reports/reconciliation/$projectNumber/detail'
    | '/projects/$employeeId/$projectNumber'
    | '/reports/reconciliation/$projectNumber'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/about'
    | '/(authenticated)/projects'
    | '/(authenticated)/form'
    | '/(authenticated)/me'
    | '/(authenticated)/personnel'
    | '/(authenticated)/reports'
    | '/(authenticated)/styles'
    | '/(authenticated)/'
    | '/(authenticated)/projects/$employeeId'
    | '/(authenticated)/accruals/'
    | '/(authenticated)/reports/'
    | '/(authenticated)/projects/$employeeId/'
    | '/(authenticated)/projects/$employeeId/$projectNumber/transactions'
    | '/(authenticated)/reports/reconciliation/$projectNumber/detail'
    | '/(authenticated)/projects/$employeeId/$projectNumber/'
    | '/(authenticated)/reports/reconciliation/$projectNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/styles': {
      id: '/(authenticated)/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof authenticatedStylesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/reports': {
      id: '/(authenticated)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof authenticatedReportsRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/personnel': {
      id: '/(authenticated)/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof authenticatedPersonnelRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/me': {
      id: '/(authenticated)/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof authenticatedMeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/form': {
      id: '/(authenticated)/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof authenticatedFormRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/projects': {
      id: '/(authenticated)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authenticatedProjectsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/reports/': {
      id: '/(authenticated)/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof authenticatedReportsIndexRouteImport
      parentRoute: typeof authenticatedReportsRoute
    }
    '/(authenticated)/accruals/': {
      id: '/(authenticated)/accruals/'
      path: '/accruals'
      fullPath: '/accruals'
      preLoaderRoute: typeof authenticatedAccrualsIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/projects/$employeeId': {
      id: '/(authenticated)/projects/$employeeId'
      path: '/$employeeId'
      fullPath: '/projects/$employeeId'
      preLoaderRoute: typeof authenticatedProjectsEmployeeIdRouteRouteImport
      parentRoute: typeof authenticatedProjectsRouteRoute
    }
    '/(authenticated)/projects/$employeeId/': {
      id: '/(authenticated)/projects/$employeeId/'
      path: '/'
      fullPath: '/projects/$employeeId/'
      preLoaderRoute: typeof authenticatedProjectsEmployeeIdIndexRouteImport
      parentRoute: typeof authenticatedProjectsEmployeeIdRouteRoute
    }
    '/(authenticated)/reports/reconciliation/$projectNumber/': {
      id: '/(authenticated)/reports/reconciliation/$projectNumber/'
      path: '/reconciliation/$projectNumber'
      fullPath: '/reports/reconciliation/$projectNumber'
      preLoaderRoute: typeof authenticatedReportsReconciliationProjectNumberIndexRouteImport
      parentRoute: typeof authenticatedReportsRoute
    }
    '/(authenticated)/projects/$employeeId/$projectNumber/': {
      id: '/(authenticated)/projects/$employeeId/$projectNumber/'
      path: '/$projectNumber'
      fullPath: '/projects/$employeeId/$projectNumber'
      preLoaderRoute: typeof authenticatedProjectsEmployeeIdProjectNumberIndexRouteImport
      parentRoute: typeof authenticatedProjectsEmployeeIdRouteRoute
    }
    '/(authenticated)/reports/reconciliation/$projectNumber/detail': {
      id: '/(authenticated)/reports/reconciliation/$projectNumber/detail'
      path: '/reconciliation/$projectNumber/detail'
      fullPath: '/reports/reconciliation/$projectNumber/detail'
      preLoaderRoute: typeof authenticatedReportsReconciliationProjectNumberDetailRouteImport
      parentRoute: typeof authenticatedReportsRoute
    }
    '/(authenticated)/projects/$employeeId/$projectNumber/transactions': {
      id: '/(authenticated)/projects/$employeeId/$projectNumber/transactions'
      path: '/$projectNumber/transactions'
      fullPath: '/projects/$employeeId/$projectNumber/transactions'
      preLoaderRoute: typeof authenticatedProjectsEmployeeIdProjectNumberTransactionsRouteImport
      parentRoute: typeof authenticatedProjectsEmployeeIdRouteRoute
    }
  }
}

interface authenticatedProjectsEmployeeIdRouteRouteChildren {
  authenticatedProjectsEmployeeIdIndexRoute: typeof authenticatedProjectsEmployeeIdIndexRoute
  authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute: typeof authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute
  authenticatedProjectsEmployeeIdProjectNumberIndexRoute: typeof authenticatedProjectsEmployeeIdProjectNumberIndexRoute
}

const authenticatedProjectsEmployeeIdRouteRouteChildren: authenticatedProjectsEmployeeIdRouteRouteChildren =
  {
    authenticatedProjectsEmployeeIdIndexRoute:
      authenticatedProjectsEmployeeIdIndexRoute,
    authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute:
      authenticatedProjectsEmployeeIdProjectNumberTransactionsRoute,
    authenticatedProjectsEmployeeIdProjectNumberIndexRoute:
      authenticatedProjectsEmployeeIdProjectNumberIndexRoute,
  }

const authenticatedProjectsEmployeeIdRouteRouteWithChildren =
  authenticatedProjectsEmployeeIdRouteRoute._addFileChildren(
    authenticatedProjectsEmployeeIdRouteRouteChildren,
  )

interface authenticatedProjectsRouteRouteChildren {
  authenticatedProjectsEmployeeIdRouteRoute: typeof authenticatedProjectsEmployeeIdRouteRouteWithChildren
}

const authenticatedProjectsRouteRouteChildren: authenticatedProjectsRouteRouteChildren =
  {
    authenticatedProjectsEmployeeIdRouteRoute:
      authenticatedProjectsEmployeeIdRouteRouteWithChildren,
  }

const authenticatedProjectsRouteRouteWithChildren =
  authenticatedProjectsRouteRoute._addFileChildren(
    authenticatedProjectsRouteRouteChildren,
  )

interface authenticatedReportsRouteChildren {
  authenticatedReportsIndexRoute: typeof authenticatedReportsIndexRoute
  authenticatedReportsReconciliationProjectNumberDetailRoute: typeof authenticatedReportsReconciliationProjectNumberDetailRoute
  authenticatedReportsReconciliationProjectNumberIndexRoute: typeof authenticatedReportsReconciliationProjectNumberIndexRoute
}

const authenticatedReportsRouteChildren: authenticatedReportsRouteChildren = {
  authenticatedReportsIndexRoute: authenticatedReportsIndexRoute,
  authenticatedReportsReconciliationProjectNumberDetailRoute:
    authenticatedReportsReconciliationProjectNumberDetailRoute,
  authenticatedReportsReconciliationProjectNumberIndexRoute:
    authenticatedReportsReconciliationProjectNumberIndexRoute,
}

const authenticatedReportsRouteWithChildren =
  authenticatedReportsRoute._addFileChildren(authenticatedReportsRouteChildren)

interface authenticatedRouteRouteChildren {
  authenticatedProjectsRouteRoute: typeof authenticatedProjectsRouteRouteWithChildren
  authenticatedFormRoute: typeof authenticatedFormRoute
  authenticatedMeRoute: typeof authenticatedMeRoute
  authenticatedPersonnelRoute: typeof authenticatedPersonnelRoute
  authenticatedReportsRoute: typeof authenticatedReportsRouteWithChildren
  authenticatedStylesRoute: typeof authenticatedStylesRoute
  authenticatedIndexRoute: typeof authenticatedIndexRoute
  authenticatedAccrualsIndexRoute: typeof authenticatedAccrualsIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedProjectsRouteRoute: authenticatedProjectsRouteRouteWithChildren,
  authenticatedFormRoute: authenticatedFormRoute,
  authenticatedMeRoute: authenticatedMeRoute,
  authenticatedPersonnelRoute: authenticatedPersonnelRoute,
  authenticatedReportsRoute: authenticatedReportsRouteWithChildren,
  authenticatedStylesRoute: authenticatedStylesRoute,
  authenticatedIndexRoute: authenticatedIndexRoute,
  authenticatedAccrualsIndexRoute: authenticatedAccrualsIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
