create table dbo.EmployeeAccrualBalances
(
    EmployeeId                 nvarchar(11) not null,
    AsOfDate                   date         not null,
    PositionNumber             nvarchar(8)  not null,
    EmployeeEmail              nvarchar(320),
    EmployeeName               nvarchar(100),
    UnionCode                  nvarchar(3),
    UnionDescription           nvarchar(50),
    EmployeeClassCode          nvarchar(3),
    EmployeeClassDescription   nvarchar(50),
    JobCode                    nvarchar(6),
    JobCodeDescription         nvarchar(50),
    ReportsToPositionNumber    nvarchar(8),
    ReportsToEmployeeId        nvarchar(11),
    ReportsToEmployeeName      nvarchar(100),
    HrStatus                   nvarchar,
    EmployeeStatus             nvarchar,
    EmployeeStatusDescription  nvarchar(30),
    EmployeeType               nvarchar,
    EmployeeTypeDescription    nvarchar(50),
    TypeLabel                  nvarchar(50),
    PrevBal                    decimal(10, 2),
    HoursTaken                 decimal(10, 2),
    AccrualHours               decimal(10, 2),
    AdjustedHours              decimal(10, 2),
    CalculatedBal              decimal(10, 2),
    AccrualLimit               decimal(10, 2),
    ApproachingMax             nvarchar,
    HoursOverUnderPolicyMax    decimal(10, 2),
    AccrualPercentage          decimal(7, 2),
    ExceptionalMaxVacationOnly int,
    Level1Dept                 nvarchar(10),
    Level1DeptDesc             nvarchar(100),
    Level2Dept                 nvarchar(10),
    Level2DeptDesc             nvarchar(100),
    Level3Dept                 nvarchar(10),
    Level3DeptDesc             nvarchar(100),
    Level4Dept                 nvarchar(10),
    Level4DeptDesc             nvarchar(100),
    Level5Dept                 nvarchar(10),
    Level5DeptDesc             nvarchar(100),
    LoadDate                   datetime2(3),
    LastUpdated                datetime2(3) not null,
    constraint PK_EmployeeAccrualBalances
        primary key (EmployeeId, AsOfDate, PositionNumber)
)
go
