CREATE TABLE dbo.FacultyDeptPortfolio
(
    ProjectNumber           NVARCHAR(30)                         NOT NULL,
    TaskNum                 NVARCHAR(30)   DEFAULT ''            NOT NULL,
    FundCode                NVARCHAR(20)   DEFAULT ''            NOT NULL,
    ProgramCode             NVARCHAR(20)   DEFAULT ''            NOT NULL,
    ActivityCode            NVARCHAR(20)   DEFAULT ''            NOT NULL,
    ExpenditureCategoryName NVARCHAR(100)  DEFAULT ''            NOT NULL,
    ProjectOwningOrgCode    NVARCHAR(20)   DEFAULT ''            NOT NULL,
    AwardNumber             NVARCHAR(100),
    AwardName               NVARCHAR(400),
    AwardType               NVARCHAR(200),
    AwardStartDate          DATE,
    AwardEndDate            DATE,
    AwardStatus             NVARCHAR(100),
    ProjectName             NVARCHAR(400),
    ProjectOwningOrg        NVARCHAR(200),
    ProjectType             NVARCHAR(100),
    ProjectStatus           NVARCHAR(100),
    TaskName                NVARCHAR(400),
    TaskStatus              NVARCHAR(100),
    Pm                      NVARCHAR(100),
    Pa                      NVARCHAR(400),
    Pi                      NVARCHAR(400),
    Copi                    NVARCHAR(400),
    FundDesc                NVARCHAR(400),
    PurposeCode             NVARCHAR(100),
    PurposeDesc             NVARCHAR(400),
    ProgramDesc             NVARCHAR(400),
    ActivityDesc            NVARCHAR(400),
    PpmBudget               DECIMAL(15, 2) DEFAULT 0             NOT NULL,
    PpmCommitments          DECIMAL(15, 2) DEFAULT 0             NOT NULL,
    PpmExpenses             DECIMAL(15, 2) DEFAULT 0             NOT NULL,
    PpmBudBal               DECIMAL(15, 2) DEFAULT 0             NOT NULL,
    LoadDate                DATETIME2(3),
    LastSyncDate            DATETIME2(3),
    LastUpdated             DATETIME2(3)   DEFAULT SYSDATETIME() NOT NULL,
    CONSTRAINT PK_FacultyDeptPortfolio
        PRIMARY KEY CLUSTERED (ProjectNumber, TaskNum, FundCode, ProgramCode, ActivityCode, ExpenditureCategoryName, ProjectOwningOrgCode)
);
GO
